[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "browser-profile-cookies"
version = "0.1.0"
authors = [
  { name="C.Kim", email="yportne8@example.com" },
]
description = "A package to decrypt encrypted cookies from your browser profile."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
]

[project.urls]
"Homepage" = "https://github.com/yportne8/profile-cookies"